### ISSUE TITLE
Unable to install the latest version on a recent project

### ISSUE THREAD

**Issue by maximelebastard** [cdklabs/cdk-watchful#404]
Hello,
I'm using a recent version of CDK on my project (1.91.0).

When running 
```
yarn add cdk-watchful -W
```

I get
```
error An unexpected error occurred: "expected hoisted manifest for \"cdk-watchful#@aws-cdk/aws-apigateway#@aws-cdk/aws-cloudwatch#@aws-cdk/core\"".
info If you think this is a bug, please open a bug report with the information provided in ".../yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

And in the yarn-error.log
```
Yarn version: 
  1.22.4

Node version: 
  14.4.0

Platform: 
  darwin x64

Trace: 
  Invariant Violation: expected hoisted manifest for "cdk-watchful#@aws-cdk/aws-apigateway#@aws-cdk/aws-cloudwatch#@aws-cdk/core"
      at invariant (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:2314:15)
      at _loop2 (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:94965:9)
      at PackageHoister.init (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:95035:19)
      at PackageLinker.getFlatHoistedTree (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:48743:20)
      at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:48754:27)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
      at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:328:14
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:5301:28)

npm manifest: 
  {
    "name": "myproject",
    "private": true,
    "version": "1.0.0",
    "workspaces": [
      "frontend/xxx",
      "backend/myfunction"
    ],
    "scripts": {
      "..."
    },
    "devDependencies": {
      "@aws-cdk/assert": "1.91.0",
      "@types/jest": "^26.0.10",
      "@types/node": "10.17.27",
      "aws-cdk": "1.91.0",
      "husky": "^4.2.5",
      "ts-node": "^9.0.0",
      "typescript": "~3.9.7"
    },
    "dependencies": {
      "@aws-cdk/aws-apigateway": "1.91.0",
      "@aws-cdk/aws-apigatewayv2-authorizers": "1.91.0",
      "@aws-cdk/aws-apigatewayv2-integrations": "1.91.0",
      "@aws-cdk/aws-appsync": "1.91.0",
      "@aws-cdk/aws-cloudfront": "1.91.0",
      "@aws-cdk/aws-codepipeline": "1.91.0",
      "@aws-cdk/aws-dynamodb": "1.91.0",
      "@aws-cdk/aws-lambda": "1.91.0",
      "@aws-cdk/aws-lambda-event-sources": "1.91.0",
      "@aws-cdk/aws-lambda-nodejs": "1.91.0",
      "@aws-cdk/aws-s3": "1.91.0",
      "@aws-cdk/aws-s3-deployment": "1.91.0",
      "@aws-cdk/aws-s3-notifications": "1.91.0",
      "@aws-cdk/aws-ses": "1.91.0",
      "@aws-cdk/core": "1.91.0",
      "@aws-cdk/pipelines": "1.91.0",
      "dotenv-safe": "^8.2.0",
      "prettier": "^2.2.1",
      "source-map-support": "^0.5.16"
    },
    "husky": {
      "hooks": {
        "pre-commit": "pretty-quick --staged"
      }
    }
  }
```

Do you know what's going on ?

**Comment by voho** [comment]
Check this - maybe related? https://github.com/yarnpkg/yarn/issues/4357
